### ISSUE TITLE
Weather API Integration

### ISSUE THREAD

**Issue by skiser** [skiser/Routinely#12]
The user will be able to get a quick view of the weather based on their location, portraying a morning afternoon and night weather update. This can be important so that the user can view the weather along with other incorporated API's. This can allow the user more usability when it comes to things. This feature can also be incorporated into a routine so that the user can choose when they would like to receive weather updates such as in the morning before they leave for work, or when they are leaving work to go home.

**Comment by ChaseTeichmann** [comment]
**Action:** 
Display Weather on alarm clock
**Design Ideas:** 
Display morning, afternoon and evening temperatures
Display important weather alerts
**Research:**
https://hackernoon.com/week-2-with-react-native-building-a-weather-app-ca50fcfcb1e1
http://www.reactnative.com/react-native-weather-app/
http://www.reactnative.com/react-native-weather-app-using-open-weather-api/
https://medium.com/@peterekeneeze/build-a-react-js-weather-app-with-stateless-functional-components-e61567004b54
