### ISSUE TITLE
Login/Authentication

### ISSUE THREAD

**Issue by skiser** [skiser/Routinely#5]
User will be able to open the app and they will be presented with the options to log in with facebook or a google account. The User will be able to choose either option or choose to make an account with just our app. Once they log in, they will be directed to the app's home page. This will allow the app to keep track of their preferences and how they are going to use the app. Our database will be linked with the information that the user uses to log in.

**Comment by pmnorris** [comment]
I will be setting up the login/authentication with Bryan. More specifically, I will be setting up the authentication process with Facebook. We will work together to figure out how we want our login page to look like.
