### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by skiser** [skiser/Routinely#6]
The User will be able to create an alarm and decide which days and time they would like the alarm to go off on. The alarm can be used for waking up or appointments or what the user would like to use an alarm for. This is a key functionality within our app to help the user being able to stay on track of things and establish a routine for when they wake up in the morning and pick which days they want to have the alarm go off/ be active. (Ideally having as many as they want without overlapping/repetition, this will allow the user to have a versatile experience as to when they want to be alerted by our app).

**Comment by ChaseTeichmann** [comment]
Action: Create an alarm
Parameters: Timestamp, Snooze Duration, Repeat Days, Repeat Alarm, Alarm Sound
Alarm Display: When the alarm goes off the application opens displaying the time with stop and snooze buttons.
Future Features: Puzzle Unlock system, Spotify API, Weather API, News API
